// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20230815171813_AddNumberOfRatings")]
    partial class AddNumberOfRatings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.TravelDest", b =>
                {
                    b.Property<int>("TravelDestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TravelDestId");

                    b.ToTable("TravelDests");

                    b.HasData(
                        new
                        {
                            TravelDestId = 1,
                            CityName = "Oslo",
                            CountryName = "Norway",
                            Rating = 9,
                            Review = "Peaceful and clean city with lots of unique art and history"
                        },
                        new
                        {
                            TravelDestId = 2,
                            CityName = "Taipei",
                            CountryName = "Tiawan",
                            Rating = 7,
                            Review = "Taroko National Park is a must see!"
                        },
                        new
                        {
                            TravelDestId = 3,
                            CityName = "Victoria BC",
                            CountryName = "Canada",
                            Rating = 8,
                            Review = "An overlooked gem. The Royal BC Museum is the single best dispaly of Native American artifacts and totem poles."
                        },
                        new
                        {
                            TravelDestId = 4,
                            CityName = "Kona",
                            CountryName = "United States of America",
                            Rating = 8,
                            Review = "Amazing beaches and shaved ice. Be sure to take a trip around the whole island. Can be done in a weekend."
                        },
                        new
                        {
                            TravelDestId = 5,
                            CityName = "Copenhagen",
                            CountryName = "Denmark",
                            Rating = 8,
                            Review = "So easy to get around by bike. Amazing bread and pastries on every corner."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
