// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20230814225441_AddValidationAttributes")]
    partial class AddValidationAttributes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.TravelDest", b =>
                {
                    b.Property<int>("TravelDestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("longtext");

                    b.HasKey("TravelDestId");

                    b.ToTable("TravelDests");

                    b.HasData(
                        new
                        {
                            TravelDestId = 1,
                            CityName = "Oslo",
                            CountryName = "Norway",
                            Rating = 9
                        },
                        new
                        {
                            TravelDestId = 2,
                            CityName = "Taipei",
                            CountryName = "Tiawan",
                            Rating = 7
                        },
                        new
                        {
                            TravelDestId = 3,
                            CityName = "Victoria",
                            CountryName = "Canada",
                            Rating = 8
                        },
                        new
                        {
                            TravelDestId = 4,
                            CityName = "Kona",
                            CountryName = "United States of America",
                            Rating = 8
                        },
                        new
                        {
                            TravelDestId = 5,
                            CityName = "Copenhagen",
                            CountryName = "Denmark",
                            Rating = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
